python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/UCI_Individual_2014_06_05_EuropeTour > IndividualEuropeTour_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/UCI_Individual_2014_06_01_WorldTour > IndividualWorldTour_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/UCI_Individual_2014_05_25_AmericaTour > IndividualAmericaTour_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_GC > IndividualGC_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_One_Day_Races > IndividualOneDay_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Prologue > IndividualPrologue_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Sprint > IndividualSprint_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Mountains > IndividualMountains_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Hills > IndividualHills_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Active_Riders > IndividualActiveRiders_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_06_Most_Efficient > IndividualMostEfficient_6_5.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Ranking_2014_06_06_Individual > IndividualPSCRank_6_5.tsv
python ScrapeGenericTeamStats.py http://www.procyclingstats.com/rankings/PCS_Ranking_2014_06_06_Teams > TeamPCSRank_6_5.tsv
python ScrapeGenericTeamStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Team_Distances > TeamDistances_6_5.tsv
python ScrapeGenericTeamStats.py http://www.procyclingstats.com/rankings/UCI_Teams_2014_06_01_WorldTour > TeamWorldTour_6_5.tsv
