#python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3789 cs_individual_europetour
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3626  cs_individual_worldtour
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3791 cs_individual_americatour
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3732 cs_individual_gc
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3733 cs_individual_oneday
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3739 cs_individual_prologue
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3744 cs_individual_sprint
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3746 cs_individual_mountains
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings.php?id=3748 cs_individual_hills
#python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2013_12_31_Active_Riders cs_individual_activeriders
#python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_06_Most_Efficient cs_individual_mostefficient 
python ScrapeGenericIndividualStats2013.py http://www.procyclingstats.com/rankings/PCS_Ranking_2013_06_30_Individual cs_individual_pcs_rank
python ScrapeGenericTeamStats2013.py http://www.procyclingstats.com/rankings.php?id=3661 cs_team_pcs_rank
python ScrapeGenericTeamStats2013.py http://www.procyclingstats.com/rankings.php?id=3443 cs_team_distances
python ScrapeGenericTeamStats2013.py http://www.procyclingstats.com/rankings.php?id=3502 cs_team_worldtour
