python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/UCI_Individual_2014_06_02_EuropeTour > IndividualEuropeTour_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/UCI_Individual_2014_06_01_WorldTour > IndividualWorldTour_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/UCI_Individual_2014_05_25_AmericaTour > IndividualAmericaTour_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_GC > IndividualGC_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_One_Day_Races > IndividualOneDay_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Prologue > IndividualPrologue_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Sprint > IndividualSprint_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Mountains > IndividualMountains_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Hills > IndividualHills_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Active_Riders > IndividualActiveRiders_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Most_Efficient > IndividualMostEfficient_6_3.tsv
python ScrapeGenericIndividualStats.py http://www.procyclingstats.com/rankings/PCS_Ranking_2014_06_01_Individual > IndividualPSCRank_6_3.tsv
python ScrapeGenericTeamStats.py http://www.procyclingstats.com/rankings/PCS_Ranking_2014_06_01_Teams > TeamPCSRank_6_3.tsv
python ScrapeGenericTeamStats.py http://www.procyclingstats.com/rankings/PCS_Specials_2014_06_01_Team_Distances > TeamDistances_6_3.tsv
python ScrapeGenericTeamStats.py http://www.procyclingstats.com/rankings/UCI_Teams_2014_06_01_WorldTour > TeamWorldTour_6_3.tsv
